import type { Metadata } from "next";
import "../globals.css";

import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import NextAuthWrapper from "@/context/next.auth.wrapper";
import ThemeRegistry from "../ThemeRegistry";
import AppProvider from "@/context/AppProvider";
import HomeHeader from "@/components/home/home.header";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextAuthWrapper>
          <AppProvider>
            <ThemeRegistry options={{ key: "joy" }}>
              <HomeHeader />
              {children}
            </ThemeRegistry>
          </AppProvider>
        </NextAuthWrapper>
      </body>
    </html>
  );
}
