import AppProvider from "@/context/AppProvider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <AppProvider>
        {children}
      </AppProvider>
        </body>
    </html>
  )
}
